[logger]
    mode = "debug"

[cron]
    interval = "*/10 * * * * *"
    time_zone = "Europe/Moscow"

[inspector]
    folders = ["logs","logs2"]              
    regexp = ["bad_text\\.(js|json)$"]

[[notifications]]
        enable = true
        name = "email"
        output_type = "email"
        host = "mail2.gloria-jeans.ru"
        port = 25
        from = "inspector@localhost.com"
        to = "kulikov@gloria-jeans.ru"
        #cc = ""
        #bcc = ""
        subject = "empty"                 
        secure = false                    
        ignore_tls = true              
        attempts = 2                       
        attempt_interval = 10